### ISSUE TITLE
Check all the files if they end with new line

### ISSUE THREAD

**Issue by mensfeld** [polishgeeks/polishgeeks-dev-tools#2]
All files in a project should have a new line ending + we should add optional ignore option

**Comment by cedricpim** [comment]
Shouldn't metadata files (like .DS_Store) be ignored by default?

**Comment by mensfeld** [comment]
They should but probably we missed something - what data files are you having that aren't ignored @cedricpim ?

**Comment by cedricpim** [comment]
.DS_Store on OSX.

**Comment by mensfeld** [comment]
@agwozdowski  could you take care of this?

**Comment by agwozdowski** [comment]
Ok, I'll care of this!
