### ISSUE TITLE
Don't complain about blank lines in archive files

### ISSUE THREAD

**Issue by kowal** [polishgeeks/polishgeeks-dev-tools#27]
I know I can omit this via config, but I think only *.rb files should be checked against final blank lines.

```
Final blank line: 207 files checked    FAILURE

Following files don't have final blank line: 
spec/support/reports/integration/weekly_reports.tar.gz
```

**Comment by mensfeld** [comment]
I disagree - we should whitelist once that shouldn,t. What about *rake, *yaml, *yml, *txt, *md  etc - it should check them as well

**Comment by agwozdowski** [comment]
Final blank line in *.rb files is checked by rubocop. This validator was written because many files like *.haml or .gitignore didn't contain final blank line. 
In this case we can consider to exclude all *.tar.gz files from this validator.

**Comment by kowal** [comment]
@agwozdowski sounds good. I would also exclude *.tar and *.bz2 extensions as well.

**Comment by mensfeld** [comment]
We shoud consider just allowing users to blacklist stuff that they dont want to check via rgexp

**Comment by agwozdowski** [comment]
@kowal for now you can exclude those files in your project by

```
config.final_blank_line_ignored = %w(
  .bz2
  .tar.gz
)
```
