### ISSUE TITLE
TargetRubyVersion

### ISSUE THREAD

**Issue by 90yukke** [polishgeeks/polishgeeks-dev-tools#43]
With new version of rubocop there's a setting `TargetRubyVersion` that has default value `1.9`. Hence it doesn't like any new feature from ruby version > 2. I think it can be set in `polishgeeks-dev-tools` to some bigger value, like 2.2 or 2.3. 

I know that I can use my own `robocop.yml`, but this setting treat just every new application as a not valid.

**Comment by mensfeld** [comment]
+1 for 2.3

**Comment by nijikon** [comment]
+1 for 2.3 from my end as well. I will work on new release during the weekend so this will go in for sure. Thanks!

**Comment by nijikon** [comment]
polishgeeks/polishgeeks-dev-tools#44

**Comment by nijikon** [comment]
Fixed in 1.3.0.
