### ISSUE TITLE
Allow vim swap files to be ignored in final_blank_line check

### ISSUE THREAD

**Issue by incazteca** [polishgeeks/polishgeeks-dev-tools#63]
Adding `*.swp` and `*.swo` in the `final_blank_line check` field of a config file will cause the the check task to fail with following error:

`RegexpError: target of repeat operator is not specified: /*.swo/`

Parser is expecting a full file name. This is inconvenient as we dont' know what files will be opened by vim while the check is running and requires the user to close their vim sessions in order to run the check.

**Comment by incazteca** [comment]
Issue traced to this line

https://github.com/polishgeeks/polishgeeks-dev-tools/blob/master/lib/polish_geeks/dev_tools/commands/final_blank_line.rb#L66

Need to have this line understand *nix globbing patterns. Otherwise it just starts to look for a file named `/*.swp`

**Comment by mensfeld** [comment]
We will fix that shortly :)
