### ISSUE TITLE
drop shoulda dependency

### ISSUE THREAD

**Issue by bartes** [polishgeeks/polishgeeks-dev-tools#75]
there is a problem with upgrading shoulda-matchers gem which is hardcoded in non-active 'shoulda' gemspec
  s.add_dependency("shoulda-context", ["~> 1.0", ">= 1.0.1"])
  s.add_dependency("shoulda-matchers", [">= 1.4.1", "< 3.0"])

do we need to have it in the gemspec ?

**Comment by nijikon** [comment]
Nope we don't.
